baseURL = 'https://castiel652.github.io/'
languageCode = 'en-us'
title = 'Random thoughts'
theme = 'paper'

[params]
    name = 'Castiel You'
    bio = 'Anyhing that comes to my mind'

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10